# Site settings
# thanks to amandavisconti@gmail.com for the Jekyll template
title: My GitHub Page

email: rlhelinski@gmail.com
description: > 
  My site for sharing things like instructions, graphic designs and recipes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rlhelinski

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
